linters:
  enable:
    - bodyclose
    - contextcheck
    - deadcode
    - depguard
    - durationcheck
    - dupl
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
